version: "2"

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Extra linters
    - dupl
    - errname
    - errorlint
    - gocritic
    - misspell
    - prealloc
    - revive
    - whitespace

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

  exclusions:
    # Log a warning if an exclusion rule is unused.
    warn-unused: true
    rules:
      # Exclude linters from test files
      - path: _test\.go$
        linters:
          # No need for `_ = errThrowingFunc()` in tests
          - errcheck

run:
  tests: true

issues:
  max-same-issues: 0
