name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24.5"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install just
        uses: extractions/setup-just@v3
        with:
          just-version: "1.40.0"

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: "v2.1.6"
          args: --timeout=5m

      - name: Run linters
        run: just lint

      - name: Run tests
        run: just test
